const VERSION = "0.1.0-tmwd-js-reverse";

const TOOL_DEFINITIONS = {
  check_browser_health: "Verify browser67-backed browser connectivity for JS reverse tasks.",
  navigate_page: "Navigate the selected page.",
  new_page: "Create a new browser page.",
  finalize_task: "Finalize js-reverse browser67-managed pages for a workspace or task.",
  list_pages: "List TMWD-visible browser pages.",
  select_page: "Select a browser page by id.",
  list_scripts: "List script tags from the selected page.",
  get_script_source: "Read inline or external script source from the selected page.",
  search_in_scripts: "Search loaded scripts by keyword or regex.",
  find_in_script: "Find text in one script source.",
  list_network_requests: "List performance and hook-captured network requests.",
  get_network_request: "Get one captured network request by id.",
  list_websocket_connections: "List websocket activity captured by hooks or performance entries.",
  get_websocket_messages: "Get websocket messages captured by hooks.",
  get_request_initiator: "Return captured call stack for a request when hook data has it.",
  get_dom_structure: "Return a compact DOM tree snapshot.",
  list_frames: "List iframes/frames with frame paths, geometry, same-origin accessibility, and child counts.",
  detect_microfrontends: "Detect possible microfrontend runtimes, iframe/shadow/sandbox boundaries, and hook-scope limits.",
  create_hook: "Create a hook definition.",
  inject_hook: "Inject a hook definition into the selected page.",
  get_hook_data: "Read hook-captured runtime records.",
  remove_hook: "Disable a hook definition.",
  list_hooks: "List server-side hook definitions.",
  hook_function: "Shortcut for create_hook + inject_hook on a function path.",
  unhook_function: "Disable a function hook.",
  monitor_events: "Monitor DOM events in the selected page.",
  stop_monitor: "Stop DOM event monitoring.",
  trace_function: "Trace calls to a function path with hook records.",
  inject_preload_script: "Inject a runtime script now and record that early preload needs a reload-capable path.",
  set_breakpoint: "Breakpoint placeholder; hooks are preferred on this browser67-backed server.",
  set_breakpoint_on_text: "Breakpoint placeholder by text search.",
  resume: "Debugger-control placeholder.",
  pause: "Debugger-control placeholder.",
  step_over: "Debugger-control placeholder.",
  step_into: "Debugger-control placeholder.",
  step_out: "Debugger-control placeholder.",
  evaluate_on_callframe: "Debugger callframe placeholder.",
  break_on_xhr: "Install fetch/xhr hooks for a URL pattern.",
  analyze_target: "One-shot reconnaissance over DOM, scripts, network, and hook records.",
  understand_code: "Local heuristic code analysis.",
  deobfuscate_code: "Lightweight local JavaScript beautification.",
  detect_crypto: "Detect common crypto/signing primitives in code.",
  summarize_code: "Summarize code shape with local heuristics.",
  risk_panel: "Score reverse-engineering risk and next-step confidence.",
  record_reverse_evidence: "Write reverse evidence to runtime artifacts.",
  export_session_report: "Export the current js-reverse session report.",
  export_evidence_bundle: "Export a reproducible js-reverse evidence bundle with summary, network rows, hooks, redacted storage, and replay notes.",
  export_rebuild_bundle: "Export a minimal Node rebuild bundle from captured evidence.",
  diff_env_requirements: "Heuristically diff browser/local environment requirements.",
  collect_code: "Collect script code snippets matching keywords.",
  collection_diff: "Diff two code collections by content hash.",
  inject_stealth: "Inject basic anti-detection overrides into the selected page.",
  set_user_agent: "Set User-Agent override through the TMWD CDP bridge.",
  save_session_state: "Save localStorage/sessionStorage/document cookie snapshot.",
  restore_session_state: "Restore localStorage/sessionStorage snapshot.",
  get_storage: "Read document cookie, localStorage, and sessionStorage.",
  get_local_storage: "Read one localStorage key with bounded value output.",
  get_session_storage: "Read one sessionStorage key with bounded value output.",
  search_storage: "Search localStorage/sessionStorage keys and bounded value previews.",
  watch_storage_changes: "Install a non-blocking storage change watcher that records storage-change hook data.",
};

const TOOL_SCHEMAS = Object.fromEntries(
  Object.entries(TOOL_DEFINITIONS).map(([name, description]) => [
    name,
    {
      description,
      inputSchema: {
        type: "object",
        properties: {
          page_id: { type: "string" },
          session_id: { type: "string" },
          session_url_pattern: { type: "string" },
          url: { type: "string" },
          script_id: { type: "string" },
          source_url: { type: "string" },
          key: { type: "string" },
          keywords: {
            type: "string",
            description: "Pipe-separated keywords, for example: sign|token|crypto.",
          },
          pattern: { type: "string" },
          request_id: { type: "string" },
          hook_id: { type: "string" },
          type: { type: "string" },
          target: { type: "string" },
          code: { type: "string" },
          events: { type: "array", items: { type: "string" } },
          view: { type: "string", enum: ["summary", "raw"] },
          max_records: { type: "number", minimum: 1, maximum: 1000 },
          max_value_chars: { type: "number", minimum: 0, maximum: 20000 },
          include_values: { type: "boolean", default: false },
          storage_area: { type: "string", enum: ["both", "localStorage", "sessionStorage"], default: "both" },
          watch_id: { type: "string" },
          channel: { type: "string" },
          task_id: { type: "string" },
          data: { type: "object" },
          evidence: { type: "object" },
          before: { type: "object" },
          after: { type: "object" },
          frame_path: { type: "string" },
          script_hashes: { type: "array", items: { type: "string" } },
          storage_keys: { type: "array", items: { type: "string" } },
          user_agent: { type: "string" },
          active: { type: "boolean", default: true },
          keep: { type: "boolean", default: false },
          fresh: { type: "boolean", default: false },
          reuse: { type: "boolean", default: true },
          ownership_policy: { type: "string", enum: ["tmwd_only", "fresh"], default: "tmwd_only" },
          reuse_scope: { type: "string", enum: ["exact", "origin_path", "origin", "none"], default: "origin_path" },
          workspace_key: { type: "string" },
          reuse_key: { type: "string" },
          navigate_reused: { type: "boolean", default: true },
          scope: { type: "string", enum: ["workspace", "task", "all"] },
          all: { type: "boolean", default: false },
          confirm_all: { type: "boolean", default: false },
          prune_stale: { type: "boolean", default: false },
          summary_only: { type: "boolean", default: false },
          dry_run: { type: "boolean", default: false },
          tmwd_mode: { type: "string", enum: ["tmwd"] },
          tmwd_transport: { type: "string", enum: ["auto", "ws", "link"] },
          tmwd_ws_endpoint: { type: "string" },
          tmwd_link_endpoint: { type: "string" },
          timeout_ms: { type: "number", minimum: 500, maximum: 120000 },
        },
      },
    },
  ]),
);

export {
  TOOL_SCHEMAS,
  VERSION,
};
