import { NATIVE_INPUT_MAX_TIMEOUT_MS } from "../native-input.mjs";

const BROWSER_CORE_TOOL_SCHEMAS = {
  browser_scan: {
    description: "GA-style web_scan: tabs + simplified content from active tab. Direct MCP default is auto; core web_scan defaults to TMWD user browser.",
    inputSchema: {
      type: "object",
      properties: {
        tabs_only: { type: "boolean", default: false },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        text_only: { type: "boolean", default: false },
        main_only: { type: "boolean", default: false },
        main_only_fallback_to_full: { type: "boolean", default: true },
        main_only_min_chars: { type: "number", minimum: 100, maximum: 10_000 },
        main_only_min_coverage: { type: "number", minimum: 0.05, maximum: 0.95 },
        max_chars: { type: "number", minimum: 1_000, maximum: 300_000 },
        cdp_endpoint: { type: "string" },
      },
    },
  },
  browser_execute_js: {
    description: "GA-style web_execute_js via TMWD bridge commands (cmd=tabs/cookies/cdp/batch) or plain JS. Direct MCP default is auto; core web_execute_js defaults to TMWD user browser.",
    inputSchema: {
      type: "object",
      properties: {
        script: { type: "string" },
        code: { type: "string" },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        no_monitor: { type: "boolean", default: false },
        native_auto_fallback: { type: "boolean", default: false },
        native_auto_fallback_policy: {
          type: "string",
          enum: ["strict", "balanced", "aggressive"],
          default: "balanced",
        },
        native_auto_execute: { type: "boolean", default: false },
        native_execute_action_scope: {
          type: "string",
          enum: ["non_pointer", "all"],
          default: "non_pointer",
        },
        native_fallback_action: {
          type: "string",
          enum: [
            "activate_window",
            "move",
            "click",
            "double_click",
            "press",
            "type",
            "paste",
            "scroll",
            "get_window_rect",
          ],
        },
        native_fallback_args: { type: "object" },
        native_fallback_timeout_ms: { type: "number", minimum: 500, maximum: NATIVE_INPUT_MAX_TIMEOUT_MS },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        output_mode: { type: "string", enum: ["full", "compact"], default: "full" },
        max_return_chars: { type: "number", minimum: 200, maximum: 300_000 },
        cdp_endpoint: { type: "string" },
        target_url_contains: { type: "string" },
      },
    },
  },
  browser_wait: {
    description: "Wait for selector/text/function/DOM-stable/network-idle conditions in the selected TMWD or CDP tab.",
    inputSchema: {
      type: "object",
      properties: {
        type: {
          type: "string",
          enum: ["selector", "text", "function", "dom_stable", "network_idle"],
          default: "selector",
        },
        selector: { type: "string" },
        text: { type: "string" },
        predicate: { type: "string" },
        code: { type: "string" },
        visible: { type: "boolean", default: true },
        stable_ms: { type: "number", minimum: 50, maximum: 30_000 },
        interval_ms: { type: "number", minimum: 25, maximum: 5_000 },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
      },
    },
  },
  browser_transport_health: {
    description: "Probe TMWD ws/link transport health and return actionable readiness diagnostics.",
    inputSchema: {
      type: "object",
      properties: {
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        timeout_ms: { type: "number", minimum: 100, maximum: 10_000 },
      },
    },
  },
  browser_run_ops: {
    description: "Create and manage externalized browser task run records under ~/.tmwd-browser-mcp/runtime/runs.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["prepare", "status", "record_event", "finish", "list"],
          default: "status",
        },
        run_id: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        group: { type: "string" },
        title: { type: "string" },
        event: { type: "string" },
        status: { type: "string" },
        data: { type: "object" },
        evidence: { type: "object" },
        summary_only: { type: "boolean", default: false },
        max_items: { type: "number", minimum: 1, maximum: 500 },
      },
    },
  },
  browser_job_ops: {
    description: "Start, inspect, fetch, and best-effort cancel in-process browser execution jobs backed by browser_execute_js.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["start", "status", "result", "cancel", "list"],
          default: "status",
        },
        job_id: { type: "string" },
        title: { type: "string" },
        workspace_key: { type: "string" },
        task_id: { type: "string" },
        run_id: { type: "string" },
        prepare_run: { type: "boolean", default: true },
        max_items: { type: "number", minimum: 1, maximum: 500 },
        script: { type: "string" },
        code: { type: "string" },
        tab_id: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        no_monitor: { type: "boolean", default: true },
        native_auto_fallback: { type: "boolean", default: false },
        native_auto_fallback_policy: {
          type: "string",
          enum: ["strict", "balanced", "aggressive"],
          default: "balanced",
        },
        native_auto_execute: { type: "boolean", default: false },
        native_execute_action_scope: {
          type: "string",
          enum: ["non_pointer", "all"],
          default: "non_pointer",
        },
        native_fallback_action: {
          type: "string",
          enum: [
            "activate_window",
            "move",
            "click",
            "double_click",
            "press",
            "type",
            "paste",
            "scroll",
            "get_window_rect",
          ],
        },
        native_fallback_args: { type: "object" },
        native_fallback_timeout_ms: { type: "number", minimum: 500, maximum: NATIVE_INPUT_MAX_TIMEOUT_MS },
        timeout_ms: { type: "number", minimum: 100, maximum: 120_000 },
        output_mode: { type: "string", enum: ["full", "compact"], default: "compact" },
        max_return_chars: { type: "number", minimum: 200, maximum: 300_000 },
        cdp_endpoint: { type: "string" },
        target_url_contains: { type: "string" },
      },
    },
  },
  browser_extract: {
    description: "Extract actionable nodes from html or active page html.",
    inputSchema: {
      type: "object",
      properties: {
        html: { type: "string" },
        selector_limit: { type: "number", minimum: 1, maximum: 300 },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
        switch_tab_id: { type: "string" },
        session_id: { type: "string" },
        session_url_pattern: { type: "string" },
      },
    },
  },
  browser_diff: {
    description: "Diff two HTML snapshots and return signatures.",
    inputSchema: {
      type: "object",
      properties: {
        before: { type: "string" },
        after: { type: "string" },
      },
      required: ["before", "after"],
    },
  },
  browser_tab_ops: {
    description: "Tab/session operations over the selected browser route (TMWD user browser or explicit remote-debugging CDP).",
    inputSchema: {
      type: "object",
      properties: {
        op: {
          type: "string",
          enum: ["list", "switch", "current", "list_sessions", "find_session", "set_session", "current_session"],
        },
        tab_id: { type: "string" },
        session_id: { type: "string" },
        url_pattern: { type: "string" },
        include_disconnected: { type: "boolean", default: false },
        include_unscriptable: { type: "boolean", default: false },
        include_internal: { type: "boolean", default: false },
        tmwd_mode: { type: "string", enum: ["auto", "tmwd", "remote_cdp", "cdp"], default: "auto" },
        tmwd_transport: { type: "string", enum: ["auto", "ws", "link"], default: "auto" },
        tmwd_ws_endpoint: { type: "string" },
        tmwd_link_endpoint: { type: "string" },
        cdp_endpoint: { type: "string" },
      },
      required: ["op"],
    },
  },
};

export { BROWSER_CORE_TOOL_SCHEMAS };
